name: quran_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  equatable: ^2.0.3
  dartz: ^0.10.1
  shimmer: ^2.0.0
  internet_connection_checker: ^0.0.1+4
  cached_network_image: ^3.2.0
  get_storage: ^2.0.3
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/lotties/